export const GET_ERRORS = 'GET_ERRORS'


export const CONNEXION = 'CONNEXION'

export const CHANGEMENT_DE_PAGE = 'CHANGEMENT_DE_PAGE'


export const RECUPERER_AUTOCOMPLETION = 'RECUPERER_AUTOCOMPLETION'

export const AJOUTER_PROSIT = 'AJOUTER_PROSIT'
export const MODIFIER_PROSIT = 'MODIFIER_PROSIT'
export const TELEVERSEMENT_PROSIT = 'TELEVERSEMENT_PROSIT'

export const PROSIT_SUPPRESSION = 'PROSIT_SUPPRESSION'

export const RECUPERER_PROSITS = 'RECUPERER_PROSITS'
export const RECUPERER_PROSIT = 'RECUPERER_PROSIT'

export const METTRE_A_JOUR_RECHERCHE = 'METTRE_A_JOUR_RECHERCHE'

export const PROSIT_CHARGEMENT = 'PROSIT_CHARGEMENT'
export const PROSITS_NON_TROUVE = 'PROSITS_NON_TROUVE'




export const AJOUTER_RESSOURCE = 'AJOUTER_RESSOURCE'
export const RESSOURCE_CHARGEMENT = 'RESSOURCE_CHARGEMENT'
export const RESSOURCE_SUPPRESSION = 'RESSOURCE_SUPPRESSION'
export const RECUPERER_RESSOURCE = 'RECUPERER_RESSOURCE'
export const RECUPERER_RESSOURCES = 'RECUPERER_RESSOURCES'
export const TELEVERSEMENT_RESSOURCE = 'TELEVERSEMENT_RESSOURCE'



export const EXPORT_CHARGEMENT = 'EXPORT_CHARGEMENT'
